<?
$PERM["bitrix"]["2"]="D";
$PERM["bitrix"]["3"]="D";
$PERM["bitrix"]["4"]="D";
$PERM["bitrix"]["8"]="D";
$PERM["bitrix"]["6"]="D";
$PERM["bitrix"]["7"]="D";
$PERM["lk-prod"]["2"]="D";
$PERM["lk-prod"]["3"]="D";
$PERM["lk-prod"]["4"]="D";
$PERM["lk-prod"]["6"]="D";
$PERM["lk-prod"]["7"]="W";
$PERM["lk-prod"]["5"]="X";
$PERM["lk-pokup"]["2"]="D";
$PERM["lk-pokup"]["3"]="D";
$PERM["lk-pokup"]["4"]="D";
$PERM["lk-pokup"]["6"]="W";
$PERM["lk-pokup"]["7"]="D";
$PERM["lk-pokup"]["5"]="X";
$PERM["search"]["5"]="W";
$PERM["products"]["5"]="W";
$PERM["services"]["5"]="W";
$PERM["index.php"]["5"]="W";
$PERM["/"]["*"]="R";
?>